option('enable_gles32', type: 'boolean', value: true, description: 'Enable usage of GLES 3.2')
option('enable_dmabuf', type: 'boolean', value: true, description: 'Enable DMA buf')
option('disable_optimizations', type: 'boolean', value: false, description: 'Disable compilation optimizations')
option('use_system_wlroots', type: 'feature', value: 'auto', description: 'Use the system-wide installation of wlroots')
option('xwayland', type: 'feature', value: 'auto', description: 'Build with xwayland support. Requires wlroots also built with xwayland support')
option('print_trace', type: 'boolean', value: true, description: 'Print stack trace in debug logs (disables coredump)')
option('tests', type: 'feature', value: 'auto', description: 'Enable unit tests')
option('custom_pch', type: 'boolean', value: false, description: 'Use custom PCH for plugins. May not work with all compilers and setups.')
option('lto', type: 'boolean', value: true, description: 'Enable Link Time Optimization')
option('pgo', type: 'boolean', value: false, description: 'Enable Profile Guided Optimization')
option('profiling', type: 'boolean', value: false, description: 'Build profile for (PGO) compilation, pgo options must be enabled')
option('asan', type: 'boolean', value: false, description: 'Enable AddressSanitizer (ASan)')
option('ubsan', type: 'boolean', value: false, description: 'Enable UndefinedBehaviorSanitizer (UBSan)')
option('tsan', type: 'boolean', value: false, description: 'Enable ThreadSanitizer (TSan)')
option('valgrind', type: 'boolean', value: false, description: 'Enable Valgrind (Memory error detector)')
option('enable_impeller', type: 'boolean', value: true, description: 'Enable Impeller rendering backend')
option('enable_vulkan', type: 'boolean', value: false, description: 'Enable Vulkan rendering backend')
option('enable_damage_history', type: 'boolean', value: true, description: 'Enable damage history tracking')
