// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * PigeonRunnerRunnerPongData:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerPongData, pigeon_runner_runner_pong_data, PIGEON_RUNNER, RUNNER_PONG_DATA, GObject)

/**
 * pigeon_runner_runner_pong_data_new:
 * pong: field in this object.
 * timestamp_ms: field in this object.
 *
 * Creates a new #RunnerPongData object.
 *
 * Returns: a new #PigeonRunnerRunnerPongData
 */
PigeonRunnerRunnerPongData* pigeon_runner_runner_pong_data_new(gboolean pong, const gchar* timestamp_ms);

/**
 * pigeon_runner_runner_pong_data_get_pong
 * @object: a #PigeonRunnerRunnerPongData.
 *
 * Gets the value of the pong field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_runner_pong_data_get_pong(PigeonRunnerRunnerPongData* object);

/**
 * pigeon_runner_runner_pong_data_get_timestamp_ms
 * @object: a #PigeonRunnerRunnerPongData.
 *
 * Gets the value of the timestampMs field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_pong_data_get_timestamp_ms(PigeonRunnerRunnerPongData* object);

/**
 * pigeon_runner_runner_pong_data_equals:
 * @a: a #PigeonRunnerRunnerPongData.
 * @b: another #PigeonRunnerRunnerPongData.
 *
 * Checks if two #PigeonRunnerRunnerPongData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean pigeon_runner_runner_pong_data_equals(PigeonRunnerRunnerPongData* a, PigeonRunnerRunnerPongData* b);

/**
 * pigeon_runner_runner_pong_data_hash:
 * @object: a #PigeonRunnerRunnerPongData.
 *
 * Calculates a hash code for a #PigeonRunnerRunnerPongData object.
 *
 * Returns: the hash code.
 */
guint pigeon_runner_runner_pong_data_hash(PigeonRunnerRunnerPongData* object);

/**
 * pigeon_runner_runner_pong_data_to_string:
 * @object: a #PigeonRunnerRunnerPongData.
 *
 * Returns a string representation of a #PigeonRunnerRunnerPongData object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* pigeon_runner_runner_pong_data_to_string(PigeonRunnerRunnerPongData* object);

/**
 * PigeonRunnerRunnerSystemInfoData:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerSystemInfoData, pigeon_runner_runner_system_info_data, PIGEON_RUNNER, RUNNER_SYSTEM_INFO_DATA, GObject)

/**
 * pigeon_runner_runner_system_info_data_new:
 * runner: field in this object.
 * version: field in this object.
 * wayland_display: field in this object.
 * width: field in this object.
 * height: field in this object.
 * pixel_ratio: field in this object.
 * fullscreen: field in this object.
 * maximized: field in this object.
 * title: field in this object.
 * app_id: field in this object.
 *
 * Creates a new #RunnerSystemInfoData object.
 *
 * Returns: a new #PigeonRunnerRunnerSystemInfoData
 */
PigeonRunnerRunnerSystemInfoData* pigeon_runner_runner_system_info_data_new(const gchar* runner, const gchar* version, const gchar* wayland_display, int64_t width, int64_t height, double pixel_ratio, gboolean fullscreen, gboolean maximized, const gchar* title, const gchar* app_id);

/**
 * pigeon_runner_runner_system_info_data_get_runner
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the runner field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_system_info_data_get_runner(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_version
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the version field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_system_info_data_get_version(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_wayland_display
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the waylandDisplay field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_system_info_data_get_wayland_display(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_width
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_runner_system_info_data_get_width(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_height
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_runner_system_info_data_get_height(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_pixel_ratio
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the pixelRatio field of @object.
 *
 * Returns: the field value.
 */
double pigeon_runner_runner_system_info_data_get_pixel_ratio(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_fullscreen
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the fullscreen field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_runner_system_info_data_get_fullscreen(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_maximized
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the maximized field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_runner_system_info_data_get_maximized(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_title
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the title field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_system_info_data_get_title(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_get_app_id
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Gets the value of the appId field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_runner_system_info_data_get_app_id(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_equals:
 * @a: a #PigeonRunnerRunnerSystemInfoData.
 * @b: another #PigeonRunnerRunnerSystemInfoData.
 *
 * Checks if two #PigeonRunnerRunnerSystemInfoData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean pigeon_runner_runner_system_info_data_equals(PigeonRunnerRunnerSystemInfoData* a, PigeonRunnerRunnerSystemInfoData* b);

/**
 * pigeon_runner_runner_system_info_data_hash:
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Calculates a hash code for a #PigeonRunnerRunnerSystemInfoData object.
 *
 * Returns: the hash code.
 */
guint pigeon_runner_runner_system_info_data_hash(PigeonRunnerRunnerSystemInfoData* object);

/**
 * pigeon_runner_runner_system_info_data_to_string:
 * @object: a #PigeonRunnerRunnerSystemInfoData.
 *
 * Returns a string representation of a #PigeonRunnerRunnerSystemInfoData object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* pigeon_runner_runner_system_info_data_to_string(PigeonRunnerRunnerSystemInfoData* object);

/**
 * PigeonRunnerCompositorPongData:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerCompositorPongData, pigeon_runner_compositor_pong_data, PIGEON_RUNNER, COMPOSITOR_PONG_DATA, GObject)

/**
 * pigeon_runner_compositor_pong_data_new:
 * pong: field in this object.
 * timestamp_us: field in this object.
 * peer_pid: field in this object.
 *
 * Creates a new #CompositorPongData object.
 *
 * Returns: a new #PigeonRunnerCompositorPongData
 */
PigeonRunnerCompositorPongData* pigeon_runner_compositor_pong_data_new(gboolean pong, int64_t timestamp_us, int64_t peer_pid);

/**
 * pigeon_runner_compositor_pong_data_get_pong
 * @object: a #PigeonRunnerCompositorPongData.
 *
 * Gets the value of the pong field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_compositor_pong_data_get_pong(PigeonRunnerCompositorPongData* object);

/**
 * pigeon_runner_compositor_pong_data_get_timestamp_us
 * @object: a #PigeonRunnerCompositorPongData.
 *
 * Gets the value of the timestampUs field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_pong_data_get_timestamp_us(PigeonRunnerCompositorPongData* object);

/**
 * pigeon_runner_compositor_pong_data_get_peer_pid
 * @object: a #PigeonRunnerCompositorPongData.
 *
 * Gets the value of the peerPid field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_pong_data_get_peer_pid(PigeonRunnerCompositorPongData* object);

/**
 * pigeon_runner_compositor_pong_data_equals:
 * @a: a #PigeonRunnerCompositorPongData.
 * @b: another #PigeonRunnerCompositorPongData.
 *
 * Checks if two #PigeonRunnerCompositorPongData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean pigeon_runner_compositor_pong_data_equals(PigeonRunnerCompositorPongData* a, PigeonRunnerCompositorPongData* b);

/**
 * pigeon_runner_compositor_pong_data_hash:
 * @object: a #PigeonRunnerCompositorPongData.
 *
 * Calculates a hash code for a #PigeonRunnerCompositorPongData object.
 *
 * Returns: the hash code.
 */
guint pigeon_runner_compositor_pong_data_hash(PigeonRunnerCompositorPongData* object);

/**
 * pigeon_runner_compositor_pong_data_to_string:
 * @object: a #PigeonRunnerCompositorPongData.
 *
 * Returns a string representation of a #PigeonRunnerCompositorPongData object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* pigeon_runner_compositor_pong_data_to_string(PigeonRunnerCompositorPongData* object);

/**
 * PigeonRunnerCompositorSystemInfoData:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerCompositorSystemInfoData, pigeon_runner_compositor_system_info_data, PIGEON_RUNNER, COMPOSITOR_SYSTEM_INFO_DATA, GObject)

/**
 * pigeon_runner_compositor_system_info_data_new:
 * compositor: field in this object.
 * version: field in this object.
 * ipc_channel: field in this object.
 * surfaces_count: field in this object.
 * client_fps: field in this object.
 * peer_pid: field in this object.
 * app_id: field in this object.
 *
 * Creates a new #CompositorSystemInfoData object.
 *
 * Returns: a new #PigeonRunnerCompositorSystemInfoData
 */
PigeonRunnerCompositorSystemInfoData* pigeon_runner_compositor_system_info_data_new(const gchar* compositor, const gchar* version, const gchar* ipc_channel, int64_t surfaces_count, double client_fps, int64_t peer_pid, const gchar* app_id);

/**
 * pigeon_runner_compositor_system_info_data_get_compositor
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the compositor field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_system_info_data_get_compositor(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_version
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the version field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_system_info_data_get_version(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_ipc_channel
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the ipcChannel field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_system_info_data_get_ipc_channel(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_surfaces_count
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the surfacesCount field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_system_info_data_get_surfaces_count(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_client_fps
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the clientFps field of @object.
 *
 * Returns: the field value.
 */
double pigeon_runner_compositor_system_info_data_get_client_fps(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_peer_pid
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the peerPid field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_system_info_data_get_peer_pid(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_get_app_id
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Gets the value of the appId field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_system_info_data_get_app_id(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_equals:
 * @a: a #PigeonRunnerCompositorSystemInfoData.
 * @b: another #PigeonRunnerCompositorSystemInfoData.
 *
 * Checks if two #PigeonRunnerCompositorSystemInfoData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean pigeon_runner_compositor_system_info_data_equals(PigeonRunnerCompositorSystemInfoData* a, PigeonRunnerCompositorSystemInfoData* b);

/**
 * pigeon_runner_compositor_system_info_data_hash:
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Calculates a hash code for a #PigeonRunnerCompositorSystemInfoData object.
 *
 * Returns: the hash code.
 */
guint pigeon_runner_compositor_system_info_data_hash(PigeonRunnerCompositorSystemInfoData* object);

/**
 * pigeon_runner_compositor_system_info_data_to_string:
 * @object: a #PigeonRunnerCompositorSystemInfoData.
 *
 * Returns a string representation of a #PigeonRunnerCompositorSystemInfoData object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* pigeon_runner_compositor_system_info_data_to_string(PigeonRunnerCompositorSystemInfoData* object);

/**
 * PigeonRunnerCompositorSurfaceData:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerCompositorSurfaceData, pigeon_runner_compositor_surface_data, PIGEON_RUNNER, COMPOSITOR_SURFACE_DATA, GObject)

/**
 * pigeon_runner_compositor_surface_data_new:
 * title: field in this object.
 * handle: field in this object.
 * app_id: field in this object.
 * width: field in this object.
 * height: field in this object.
 * fullscreen: field in this object.
 * maximized: field in this object.
 * activated: field in this object.
 *
 * Creates a new #CompositorSurfaceData object.
 *
 * Returns: a new #PigeonRunnerCompositorSurfaceData
 */
PigeonRunnerCompositorSurfaceData* pigeon_runner_compositor_surface_data_new(const gchar* title, int64_t handle, const gchar* app_id, int64_t width, int64_t height, gboolean fullscreen, gboolean maximized, gboolean activated);

/**
 * pigeon_runner_compositor_surface_data_get_title
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the title field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_surface_data_get_title(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_handle
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the handle field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_surface_data_get_handle(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_app_id
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the appId field of @object.
 *
 * Returns: the field value.
 */
const gchar* pigeon_runner_compositor_surface_data_get_app_id(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_width
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_surface_data_get_width(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_height
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t pigeon_runner_compositor_surface_data_get_height(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_fullscreen
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the fullscreen field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_compositor_surface_data_get_fullscreen(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_maximized
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the maximized field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_compositor_surface_data_get_maximized(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_get_activated
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Gets the value of the activated field of @object.
 *
 * Returns: the field value.
 */
gboolean pigeon_runner_compositor_surface_data_get_activated(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_equals:
 * @a: a #PigeonRunnerCompositorSurfaceData.
 * @b: another #PigeonRunnerCompositorSurfaceData.
 *
 * Checks if two #PigeonRunnerCompositorSurfaceData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean pigeon_runner_compositor_surface_data_equals(PigeonRunnerCompositorSurfaceData* a, PigeonRunnerCompositorSurfaceData* b);

/**
 * pigeon_runner_compositor_surface_data_hash:
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Calculates a hash code for a #PigeonRunnerCompositorSurfaceData object.
 *
 * Returns: the hash code.
 */
guint pigeon_runner_compositor_surface_data_hash(PigeonRunnerCompositorSurfaceData* object);

/**
 * pigeon_runner_compositor_surface_data_to_string:
 * @object: a #PigeonRunnerCompositorSurfaceData.
 *
 * Returns a string representation of a #PigeonRunnerCompositorSurfaceData object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* pigeon_runner_compositor_surface_data_to_string(PigeonRunnerCompositorSurfaceData* object);

G_DECLARE_FINAL_TYPE(PigeonRunnerMessageCodec, pigeon_runner_message_codec, PIGEON_RUNNER, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int pigeon_runner_runner_pong_data_type_id;
extern const int pigeon_runner_runner_system_info_data_type_id;
extern const int pigeon_runner_compositor_pong_data_type_id;
extern const int pigeon_runner_compositor_system_info_data_type_id;
extern const int pigeon_runner_compositor_surface_data_type_id;

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerHostApi, pigeon_runner_runner_host_api, PIGEON_RUNNER, RUNNER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerHostApiResponseHandle, pigeon_runner_runner_host_api_response_handle, PIGEON_RUNNER, RUNNER_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * PigeonRunnerRunnerHostApiVTable:
 *
 * Table of functions exposed by RunnerHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*get_system_info)(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_window_title)(const gchar* title, PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_fullscreen)(gboolean enabled, PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_maximized)(gboolean enabled, PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*minimize)(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*ping)(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gpointer user_data);
} PigeonRunnerRunnerHostApiVTable;

/**
 * pigeon_runner_runner_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the RunnerHostApi API.
 */
void pigeon_runner_runner_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const PigeonRunnerRunnerHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * pigeon_runner_runner_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the RunnerHostApi API.
 */
void pigeon_runner_runner_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * pigeon_runner_runner_host_api_respond_get_system_info:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.getSystemInfo. 
 */
void pigeon_runner_runner_host_api_respond_get_system_info(PigeonRunnerRunnerHostApiResponseHandle* response_handle, PigeonRunnerRunnerSystemInfoData* return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_get_system_info:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.getSystemInfo. 
 */
void pigeon_runner_runner_host_api_respond_error_get_system_info(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_api_respond_set_window_title:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.setWindowTitle. 
 */
void pigeon_runner_runner_host_api_respond_set_window_title(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_set_window_title:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.setWindowTitle. 
 */
void pigeon_runner_runner_host_api_respond_error_set_window_title(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_api_respond_set_fullscreen:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.setFullscreen. 
 */
void pigeon_runner_runner_host_api_respond_set_fullscreen(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_set_fullscreen:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.setFullscreen. 
 */
void pigeon_runner_runner_host_api_respond_error_set_fullscreen(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_api_respond_set_maximized:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.setMaximized. 
 */
void pigeon_runner_runner_host_api_respond_set_maximized(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_set_maximized:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.setMaximized. 
 */
void pigeon_runner_runner_host_api_respond_error_set_maximized(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_api_respond_minimize:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.minimize. 
 */
void pigeon_runner_runner_host_api_respond_minimize(PigeonRunnerRunnerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_minimize:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.minimize. 
 */
void pigeon_runner_runner_host_api_respond_error_minimize(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_api_respond_ping:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostApi.ping. 
 */
void pigeon_runner_runner_host_api_respond_ping(PigeonRunnerRunnerHostApiResponseHandle* response_handle, PigeonRunnerRunnerPongData* return_value);

/**
 * pigeon_runner_runner_host_api_respond_error_ping:
 * @response_handle: a #PigeonRunnerRunnerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostApi.ping. 
 */
void pigeon_runner_runner_host_api_respond_error_ping(PigeonRunnerRunnerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerHostIpcApi, pigeon_runner_runner_host_ipc_api, PIGEON_RUNNER, RUNNER_HOST_IPC_API, GObject)

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerHostIpcApiResponseHandle, pigeon_runner_runner_host_ipc_api_response_handle, PIGEON_RUNNER, RUNNER_HOST_IPC_API_RESPONSE_HANDLE, GObject)

/**
 * PigeonRunnerRunnerHostIpcApiVTable:
 *
 * Table of functions exposed by RunnerHostIpcApi to be implemented by the API provider.
 */
typedef struct {
  void (*get_compositor_info)(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, gpointer user_data);
  void (*ping_compositor)(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, gpointer user_data);
  void (*list_surfaces)(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, gpointer user_data);
  void (*close_surface)(int64_t surface_handle, PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, gpointer user_data);
} PigeonRunnerRunnerHostIpcApiVTable;

/**
 * pigeon_runner_runner_host_ipc_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the RunnerHostIpcApi API.
 */
void pigeon_runner_runner_host_ipc_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const PigeonRunnerRunnerHostIpcApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * pigeon_runner_runner_host_ipc_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the RunnerHostIpcApi API.
 */
void pigeon_runner_runner_host_ipc_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * pigeon_runner_runner_host_ipc_api_respond_get_compositor_info:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostIpcApi.getCompositorInfo. 
 */
void pigeon_runner_runner_host_ipc_api_respond_get_compositor_info(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, PigeonRunnerCompositorSystemInfoData* return_value);

/**
 * pigeon_runner_runner_host_ipc_api_respond_error_get_compositor_info:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostIpcApi.getCompositorInfo. 
 */
void pigeon_runner_runner_host_ipc_api_respond_error_get_compositor_info(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_ipc_api_respond_ping_compositor:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostIpcApi.pingCompositor. 
 */
void pigeon_runner_runner_host_ipc_api_respond_ping_compositor(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, PigeonRunnerCompositorPongData* return_value);

/**
 * pigeon_runner_runner_host_ipc_api_respond_error_ping_compositor:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostIpcApi.pingCompositor. 
 */
void pigeon_runner_runner_host_ipc_api_respond_error_ping_compositor(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_ipc_api_respond_list_surfaces:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostIpcApi.listSurfaces. 
 */
void pigeon_runner_runner_host_ipc_api_respond_list_surfaces(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, FlValue* return_value);

/**
 * pigeon_runner_runner_host_ipc_api_respond_error_list_surfaces:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostIpcApi.listSurfaces. 
 */
void pigeon_runner_runner_host_ipc_api_respond_error_list_surfaces(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * pigeon_runner_runner_host_ipc_api_respond_close_surface:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to RunnerHostIpcApi.closeSurface. 
 */
void pigeon_runner_runner_host_ipc_api_respond_close_surface(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, gboolean return_value);

/**
 * pigeon_runner_runner_host_ipc_api_respond_error_close_surface:
 * @response_handle: a #PigeonRunnerRunnerHostIpcApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to RunnerHostIpcApi.closeSurface. 
 */
void pigeon_runner_runner_host_ipc_api_respond_error_close_surface(PigeonRunnerRunnerHostIpcApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse, pigeon_runner_runner_flutter_ipc_api_on_notification_response, PIGEON_RUNNER, RUNNER_FLUTTER_IPC_API_ON_NOTIFICATION_RESPONSE, GObject)

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification_response_is_error:
 * @response: a #PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse.
 *
 * Checks if a response to RunnerFlutterIpcApi.onNotification is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean pigeon_runner_runner_flutter_ipc_api_on_notification_response_is_error(PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse* response);

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_code:
 * @response: a #PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_code(PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse* response);

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_message:
 * @response: a #PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_message(PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse* response);

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_details:
 * @response: a #PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* pigeon_runner_runner_flutter_ipc_api_on_notification_response_get_error_details(PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse* response);

/**
 * PigeonRunnerRunnerFlutterIpcApi:
 *
 */

G_DECLARE_FINAL_TYPE(PigeonRunnerRunnerFlutterIpcApi, pigeon_runner_runner_flutter_ipc_api, PIGEON_RUNNER, RUNNER_FLUTTER_IPC_API, GObject)

/**
 * pigeon_runner_runner_flutter_ipc_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the RunnerFlutterIpcApi API.
 *
 * Returns: a new #PigeonRunnerRunnerFlutterIpcApi
 */
PigeonRunnerRunnerFlutterIpcApi* pigeon_runner_runner_flutter_ipc_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification:
 * @api: a #PigeonRunnerRunnerFlutterIpcApi.
 * @method: parameter for this method.
 * @params_json: (allow-none): parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void pigeon_runner_runner_flutter_ipc_api_on_notification(PigeonRunnerRunnerFlutterIpcApi* api, const gchar* method, const gchar* params_json, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * pigeon_runner_runner_flutter_ipc_api_on_notification_finish:
 * @api: a #PigeonRunnerRunnerFlutterIpcApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a pigeon_runner_runner_flutter_ipc_api_on_notification() call.
 *
 * Returns: a #PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse or %NULL on error.
 */
PigeonRunnerRunnerFlutterIpcApiOnNotificationResponse* pigeon_runner_runner_flutter_ipc_api_on_notification_finish(PigeonRunnerRunnerFlutterIpcApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
