// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class RunnerPongData {
  RunnerPongData({required this.pong, required this.timestampMs});

  bool pong;

  String timestampMs;

  List<Object?> _toList() {
    return <Object?>[pong, timestampMs];
  }

  Object encode() {
    return _toList();
  }

  static RunnerPongData decode(Object result) {
    result as List<Object?>;
    return RunnerPongData(
      pong: result[0]! as bool,
      timestampMs: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RunnerPongData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pong, other.pong) &&
        _deepEquals(timestampMs, other.timestampMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RunnerPongData(pong: $pong, timestampMs: $timestampMs)';
  }
}

class RunnerSystemInfoData {
  RunnerSystemInfoData({
    required this.runner,
    required this.version,
    required this.waylandDisplay,
    required this.width,
    required this.height,
    required this.pixelRatio,
    required this.fullscreen,
    required this.maximized,
    required this.title,
    required this.appId,
  });

  String runner;

  String version;

  String waylandDisplay;

  int width;

  int height;

  double pixelRatio;

  bool fullscreen;

  bool maximized;

  String title;

  String appId;

  List<Object?> _toList() {
    return <Object?>[
      runner,
      version,
      waylandDisplay,
      width,
      height,
      pixelRatio,
      fullscreen,
      maximized,
      title,
      appId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RunnerSystemInfoData decode(Object result) {
    result as List<Object?>;
    return RunnerSystemInfoData(
      runner: result[0]! as String,
      version: result[1]! as String,
      waylandDisplay: result[2]! as String,
      width: result[3]! as int,
      height: result[4]! as int,
      pixelRatio: result[5]! as double,
      fullscreen: result[6]! as bool,
      maximized: result[7]! as bool,
      title: result[8]! as String,
      appId: result[9]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RunnerSystemInfoData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runner, other.runner) &&
        _deepEquals(version, other.version) &&
        _deepEquals(waylandDisplay, other.waylandDisplay) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(pixelRatio, other.pixelRatio) &&
        _deepEquals(fullscreen, other.fullscreen) &&
        _deepEquals(maximized, other.maximized) &&
        _deepEquals(title, other.title) &&
        _deepEquals(appId, other.appId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RunnerSystemInfoData(runner: $runner, version: $version, waylandDisplay: $waylandDisplay, width: $width, height: $height, pixelRatio: $pixelRatio, fullscreen: $fullscreen, maximized: $maximized, title: $title, appId: $appId)';
  }
}

class CompositorPongData {
  CompositorPongData({
    required this.pong,
    required this.timestampUs,
    required this.peerPid,
  });

  bool pong;

  int timestampUs;

  int peerPid;

  List<Object?> _toList() {
    return <Object?>[pong, timestampUs, peerPid];
  }

  Object encode() {
    return _toList();
  }

  static CompositorPongData decode(Object result) {
    result as List<Object?>;
    return CompositorPongData(
      pong: result[0]! as bool,
      timestampUs: result[1]! as int,
      peerPid: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositorPongData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pong, other.pong) &&
        _deepEquals(timestampUs, other.timestampUs) &&
        _deepEquals(peerPid, other.peerPid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompositorPongData(pong: $pong, timestampUs: $timestampUs, peerPid: $peerPid)';
  }
}

class CompositorSystemInfoData {
  CompositorSystemInfoData({
    required this.compositor,
    required this.version,
    required this.ipcChannel,
    required this.surfacesCount,
    required this.clientFps,
    required this.peerPid,
    required this.appId,
  });

  String compositor;

  String version;

  String ipcChannel;

  int surfacesCount;

  double clientFps;

  int peerPid;

  String appId;

  List<Object?> _toList() {
    return <Object?>[
      compositor,
      version,
      ipcChannel,
      surfacesCount,
      clientFps,
      peerPid,
      appId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CompositorSystemInfoData decode(Object result) {
    result as List<Object?>;
    return CompositorSystemInfoData(
      compositor: result[0]! as String,
      version: result[1]! as String,
      ipcChannel: result[2]! as String,
      surfacesCount: result[3]! as int,
      clientFps: result[4]! as double,
      peerPid: result[5]! as int,
      appId: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositorSystemInfoData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(compositor, other.compositor) &&
        _deepEquals(version, other.version) &&
        _deepEquals(ipcChannel, other.ipcChannel) &&
        _deepEquals(surfacesCount, other.surfacesCount) &&
        _deepEquals(clientFps, other.clientFps) &&
        _deepEquals(peerPid, other.peerPid) &&
        _deepEquals(appId, other.appId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompositorSystemInfoData(compositor: $compositor, version: $version, ipcChannel: $ipcChannel, surfacesCount: $surfacesCount, clientFps: $clientFps, peerPid: $peerPid, appId: $appId)';
  }
}

class CompositorSurfaceData {
  CompositorSurfaceData({
    required this.title,
    required this.handle,
    required this.appId,
    required this.width,
    required this.height,
    required this.fullscreen,
    required this.maximized,
    required this.activated,
  });

  String title;

  int handle;

  String appId;

  int width;

  int height;

  bool fullscreen;

  bool maximized;

  bool activated;

  List<Object?> _toList() {
    return <Object?>[
      title,
      handle,
      appId,
      width,
      height,
      fullscreen,
      maximized,
      activated,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CompositorSurfaceData decode(Object result) {
    result as List<Object?>;
    return CompositorSurfaceData(
      title: result[0]! as String,
      handle: result[1]! as int,
      appId: result[2]! as String,
      width: result[3]! as int,
      height: result[4]! as int,
      fullscreen: result[5]! as bool,
      maximized: result[6]! as bool,
      activated: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositorSurfaceData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(handle, other.handle) &&
        _deepEquals(appId, other.appId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(fullscreen, other.fullscreen) &&
        _deepEquals(maximized, other.maximized) &&
        _deepEquals(activated, other.activated);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompositorSurfaceData(title: $title, handle: $handle, appId: $appId, width: $width, height: $height, fullscreen: $fullscreen, maximized: $maximized, activated: $activated)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RunnerPongData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RunnerSystemInfoData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CompositorPongData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CompositorSystemInfoData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is CompositorSurfaceData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return RunnerPongData.decode(readValue(buffer)!);
      case 130:
        return RunnerSystemInfoData.decode(readValue(buffer)!);
      case 131:
        return CompositorPongData.decode(readValue(buffer)!);
      case 132:
        return CompositorSystemInfoData.decode(readValue(buffer)!);
      case 133:
        return CompositorSurfaceData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RunnerHostApi {
  /// Constructor for [RunnerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RunnerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<RunnerSystemInfoData?> getSystemInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.getSystemInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as RunnerSystemInfoData?;
  }

  Future<bool> setWindowTitle(String title) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setWindowTitle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[title],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> setFullscreen({bool enabled = false}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setFullscreen$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> setMaximized({bool enabled = false}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setMaximized$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> minimize() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.minimize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<RunnerPongData> ping() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostApi.ping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RunnerPongData;
  }
}

class RunnerHostIpcApi {
  /// Constructor for [RunnerHostIpcApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RunnerHostIpcApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CompositorSystemInfoData?> getCompositorInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.getCompositorInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as CompositorSystemInfoData?;
  }

  Future<CompositorPongData?> pingCompositor() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.pingCompositor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as CompositorPongData?;
  }

  Future<List<CompositorSurfaceData>?> listSurfaces() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.listSurfaces$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return (pigeonVar_replyValue as List<Object?>?)
        ?.cast<CompositorSurfaceData>();
  }

  Future<bool> closeSurface(int surfaceHandle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.closeSurface$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[surfaceHandle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

abstract class RunnerFlutterIpcApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNotification(String method, String? paramsJson);

  static void setUp(
    RunnerFlutterIpcApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pigeon_runner.RunnerFlutterIpcApi.onNotification$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_method = args[0]! as String;
          final String? arg_paramsJson = args[1] as String?;
          try {
            api.onNotification(arg_method, arg_paramsJson);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
