// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace sparrow {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class RunnerPongData {
 public:
  // Constructs an object setting all fields.
  explicit RunnerPongData(
    bool pong,
    const std::string& timestamp_ms);

  bool pong() const;
  void set_pong(bool value_arg);

  const std::string& timestamp_ms() const;
  void set_timestamp_ms(std::string_view value_arg);

  bool operator==(const RunnerPongData& other) const;
  bool operator!=(const RunnerPongData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const RunnerPongData& obj);
 private:
  static RunnerPongData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  friend class PigeonInternalCodecSerializer;
  bool pong_;
  std::string timestamp_ms_;
};


// Generated class from Pigeon that represents data sent in messages.
class RunnerSystemInfoData {
 public:
  // Constructs an object setting all fields.
  explicit RunnerSystemInfoData(
    const std::string& runner,
    const std::string& version,
    const std::string& wayland_display,
    int64_t width,
    int64_t height,
    double pixel_ratio,
    bool fullscreen,
    bool maximized,
    const std::string& title,
    const std::string& app_id);

  const std::string& runner() const;
  void set_runner(std::string_view value_arg);

  const std::string& version() const;
  void set_version(std::string_view value_arg);

  const std::string& wayland_display() const;
  void set_wayland_display(std::string_view value_arg);

  int64_t width() const;
  void set_width(int64_t value_arg);

  int64_t height() const;
  void set_height(int64_t value_arg);

  double pixel_ratio() const;
  void set_pixel_ratio(double value_arg);

  bool fullscreen() const;
  void set_fullscreen(bool value_arg);

  bool maximized() const;
  void set_maximized(bool value_arg);

  const std::string& title() const;
  void set_title(std::string_view value_arg);

  const std::string& app_id() const;
  void set_app_id(std::string_view value_arg);

  bool operator==(const RunnerSystemInfoData& other) const;
  bool operator!=(const RunnerSystemInfoData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const RunnerSystemInfoData& obj);
 private:
  static RunnerSystemInfoData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  friend class PigeonInternalCodecSerializer;
  std::string runner_;
  std::string version_;
  std::string wayland_display_;
  int64_t width_;
  int64_t height_;
  double pixel_ratio_;
  bool fullscreen_;
  bool maximized_;
  std::string title_;
  std::string app_id_;
};


// Generated class from Pigeon that represents data sent in messages.
class CompositorPongData {
 public:
  // Constructs an object setting all fields.
  explicit CompositorPongData(
    bool pong,
    int64_t timestamp_us,
    int64_t peer_pid);

  bool pong() const;
  void set_pong(bool value_arg);

  int64_t timestamp_us() const;
  void set_timestamp_us(int64_t value_arg);

  int64_t peer_pid() const;
  void set_peer_pid(int64_t value_arg);

  bool operator==(const CompositorPongData& other) const;
  bool operator!=(const CompositorPongData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const CompositorPongData& obj);
 private:
  static CompositorPongData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  friend class PigeonInternalCodecSerializer;
  bool pong_;
  int64_t timestamp_us_;
  int64_t peer_pid_;
};


// Generated class from Pigeon that represents data sent in messages.
class CompositorSystemInfoData {
 public:
  // Constructs an object setting all fields.
  explicit CompositorSystemInfoData(
    const std::string& compositor,
    const std::string& version,
    const std::string& ipc_channel,
    int64_t surfaces_count,
    double client_fps,
    int64_t peer_pid,
    const std::string& app_id);

  const std::string& compositor() const;
  void set_compositor(std::string_view value_arg);

  const std::string& version() const;
  void set_version(std::string_view value_arg);

  const std::string& ipc_channel() const;
  void set_ipc_channel(std::string_view value_arg);

  int64_t surfaces_count() const;
  void set_surfaces_count(int64_t value_arg);

  double client_fps() const;
  void set_client_fps(double value_arg);

  int64_t peer_pid() const;
  void set_peer_pid(int64_t value_arg);

  const std::string& app_id() const;
  void set_app_id(std::string_view value_arg);

  bool operator==(const CompositorSystemInfoData& other) const;
  bool operator!=(const CompositorSystemInfoData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const CompositorSystemInfoData& obj);
 private:
  static CompositorSystemInfoData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  friend class PigeonInternalCodecSerializer;
  std::string compositor_;
  std::string version_;
  std::string ipc_channel_;
  int64_t surfaces_count_;
  double client_fps_;
  int64_t peer_pid_;
  std::string app_id_;
};


// Generated class from Pigeon that represents data sent in messages.
class CompositorSurfaceData {
 public:
  // Constructs an object setting all fields.
  explicit CompositorSurfaceData(
    const std::string& title,
    int64_t handle,
    const std::string& app_id,
    int64_t width,
    int64_t height,
    bool fullscreen,
    bool maximized,
    bool activated);

  const std::string& title() const;
  void set_title(std::string_view value_arg);

  int64_t handle() const;
  void set_handle(int64_t value_arg);

  const std::string& app_id() const;
  void set_app_id(std::string_view value_arg);

  int64_t width() const;
  void set_width(int64_t value_arg);

  int64_t height() const;
  void set_height(int64_t value_arg);

  bool fullscreen() const;
  void set_fullscreen(bool value_arg);

  bool maximized() const;
  void set_maximized(bool value_arg);

  bool activated() const;
  void set_activated(bool value_arg);

  bool operator==(const CompositorSurfaceData& other) const;
  bool operator!=(const CompositorSurfaceData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const CompositorSurfaceData& obj);
 private:
  static CompositorSurfaceData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class RunnerHostApi;
  friend class RunnerHostIpcApi;
  friend class RunnerFlutterIpcApi;
  friend class PigeonInternalCodecSerializer;
  std::string title_;
  int64_t handle_;
  std::string app_id_;
  int64_t width_;
  int64_t height_;
  bool fullscreen_;
  bool maximized_;
  bool activated_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class RunnerHostApi {
 public:
  RunnerHostApi(const RunnerHostApi&) = delete;
  RunnerHostApi& operator=(const RunnerHostApi&) = delete;
  virtual ~RunnerHostApi() {}
  virtual void GetSystemInfo(std::function<void(ErrorOr<std::optional<RunnerSystemInfoData>> reply)> result) = 0;
  virtual void SetWindowTitle(
    const std::string& title,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetFullscreen(
    bool enabled,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetMaximized(
    bool enabled,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void Minimize(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void Ping(std::function<void(ErrorOr<RunnerPongData> reply)> result) = 0;

  // The codec used by RunnerHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `RunnerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    RunnerHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    RunnerHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  RunnerHostApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class RunnerHostIpcApi {
 public:
  RunnerHostIpcApi(const RunnerHostIpcApi&) = delete;
  RunnerHostIpcApi& operator=(const RunnerHostIpcApi&) = delete;
  virtual ~RunnerHostIpcApi() {}
  virtual void GetCompositorInfo(std::function<void(ErrorOr<std::optional<CompositorSystemInfoData>> reply)> result) = 0;
  virtual void PingCompositor(std::function<void(ErrorOr<std::optional<CompositorPongData>> reply)> result) = 0;
  virtual void ListSurfaces(std::function<void(ErrorOr<std::optional<::flutter::EncodableList>> reply)> result) = 0;
  virtual void CloseSurface(
    int64_t surface_handle,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by RunnerHostIpcApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `RunnerHostIpcApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    RunnerHostIpcApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    RunnerHostIpcApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  RunnerHostIpcApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class RunnerFlutterIpcApi {
 public:
  RunnerFlutterIpcApi(::flutter::BinaryMessenger* binary_messenger);
  RunnerFlutterIpcApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void OnNotification(
    const std::string& method,
    const std::string* params_json,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace sparrow
#endif  // PIGEON_MESSAGES_G_H_
