// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace sparrow
{
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name)
{
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

namespace
{
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b)
{
    return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b)
{
    if (a.size() != b.size())
    {
        return false;
    }

    for (size_t i = 0; i < a.size(); ++i)
    {
        if (!PigeonInternalDeepEquals(a[i], b[i]))
        {
            return false;
        }
    }

    return true;
}

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b)
{
    if (a.size() != b.size())
    {
        return false;
    }

    for (const auto& kv : a)
    {
        bool found = false;
        for (const auto& b_kv : b)
        {
            if (PigeonInternalDeepEquals(kv.first, b_kv.first))
            {
                if (PigeonInternalDeepEquals(kv.second, b_kv.second))
                {
                    found = true;
                    break;
                } else
                {
                    return false;
                }
            }
        }

        if (!found)
        {
            return false;
        }
    }

    return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b)
{
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b)
{
    if (!a && !b)
    {
        return true;
    }

    if (!a || !b)
    {
        return false;
    }

    return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b)
{
    if (a.get() == b.get())
    {
        return true;
    }

    if (!a || !b)
    {
        return false;
    }

    return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b)
{
    if (a.index() != b.index())
    {
        return false;
    }

    if (const double *da = std::get_if<double>(&a))
    {
        return PigeonInternalDeepEquals(*da, std::get<double>(b));
    } else if (const ::flutter::EncodableList *la = std::get_if<::flutter::EncodableList>(&a))
    {
        return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
    } else if (const ::flutter::EncodableMap *ma = std::get_if<::flutter::EncodableMap>(&a))
    {
        return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
    }

    return a == b;
}

template<typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template<typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template<typename T>
size_t PigeonInternalDeepHash(const T& v)
{
    return std::hash<T>()(v);
}

template<typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v)
{
    size_t result = 1;
    for (const auto& item : v)
    {
        result = result * 31 + PigeonInternalDeepHash(item);
    }

    return result;
}

template<typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v)
{
    size_t result = 0;
    for (const auto& kv : v)
    {
        result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
    }

    return result;
}

size_t PigeonInternalDeepHash(const double& v)
{
    if (std::isnan(v))
    {
        // Normalize NaN to a consistent hash.
        return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
    }

    if (v == 0.0)
    {
        // Normalize -0.0 to 0.0 so they have the same hash code.
        return std::hash<double>()(0.0);
    }

    return std::hash<double>()(v);
}

template<typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v)
{
    return v ? PigeonInternalDeepHash(*v) : 0;
}

template<typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v)
{
    return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v)
{
    size_t result = v.index();
    if (const double *dv = std::get_if<double>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*dv);
    } else if (const ::flutter::EncodableList *lv =
                   std::get_if<::flutter::EncodableList>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*lv);
    } else if (const ::flutter::EncodableMap *mv =
                   std::get_if<::flutter::EncodableMap>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*mv);
    } else
    {
        std::visit(
            [&result] (const auto& val)
        {
            using T = std::decay_t<decltype(val)>;
            if constexpr (!std::is_same_v<T, double> &&
                          !std::is_same_v<T, ::flutter::EncodableList> &&
                          !std::is_same_v<T, ::flutter::EncodableMap> &&
                          !std::is_same_v<T, std::monostate> &&
                          !std::is_same_v<T, ::flutter::CustomEncodableValue> )
            {
                result = result * 31 + PigeonInternalDeepHash(val);
            }
        },
            v);
    }

    return result;
}

template<typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template<typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template<typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template<typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template<typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template<typename T>
std::string PigeonInternalToString(const T& v)
{
    std::stringstream ss;
    if constexpr (std::is_enum_v<T> )
    {
        ss << static_cast<int>(v);
    } else
    {
        ss << v;
    }

    return ss.str();
}

std::string PigeonInternalToString(const bool& v)
{
    return v ? "true" : "false";
}

template<typename T>
std::string PigeonInternalToString(const std::vector<T>& v)
{
    std::stringstream ss;
    ss << "[";
    for (size_t i = 0; i < v.size(); ++i)
    {
        if (i > 0)
        {
            ss << ", ";
        }

        ss << PigeonInternalToString(v[i]);
    }

    ss << "]";
    return ss.str();
}

template<typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v)
{
    std::stringstream ss;
    ss << "{";
    bool first = true;
    for (const auto& kv : v)
    {
        if (!first)
        {
            ss << ", ";
        }

        first = false;
        ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
    }

    ss << "}";
    return ss.str();
}

template<typename T>
std::string PigeonInternalToString(const std::optional<T>& v)
{
    return v ? PigeonInternalToString(*v) : "null";
}

template<typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v)
{
    return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v)
{
    return std::visit(
        [] (const auto& val)
    {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate> )
        {
            return std::string("null");
        } else if constexpr (std::is_same_v<T, bool> )
        {
            return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string> )
        {
            return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue> )
        {
            return std::string("[custom]");
        } else
        {
            return PigeonInternalToString(val);
        }
    },
        v);
}
} // namespace

// RunnerPongData

RunnerPongData::RunnerPongData(
    bool pong,
    const std::string& timestamp_ms) :
    pong_(pong),
    timestamp_ms_(timestamp_ms)
{}

bool RunnerPongData::pong() const
{
    return pong_;
}

void RunnerPongData::set_pong(bool value_arg)
{
    pong_ = value_arg;
}

const std::string& RunnerPongData::timestamp_ms() const
{
    return timestamp_ms_;
}

void RunnerPongData::set_timestamp_ms(std::string_view value_arg)
{
    timestamp_ms_ = value_arg;
}

EncodableList RunnerPongData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(2);
    list.push_back(EncodableValue(pong_));
    list.push_back(EncodableValue(timestamp_ms_));
    return list;
}

RunnerPongData RunnerPongData::FromEncodableList(const EncodableList& list)
{
    RunnerPongData decoded(
        std::get<bool>(list[0]),
        std::get<std::string>(list[1]));
    return decoded;
}

bool RunnerPongData::operator ==(const RunnerPongData& other) const
{
    return PigeonInternalDeepEquals(pong_, other.pong_) && PigeonInternalDeepEquals(timestamp_ms_,
        other.timestamp_ms_);
}

bool RunnerPongData::operator !=(const RunnerPongData& other) const
{
    return !(*this == other);
}

size_t RunnerPongData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(pong_);
    result = result * 31 + PigeonInternalDeepHash(timestamp_ms_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const RunnerPongData& obj)
{
    os << "RunnerPongData(";
    os << "pong: ";
    os << PigeonInternalToString(obj.pong_);
    os << ", timestamp_ms: ";
    os << PigeonInternalToString(obj.timestamp_ms_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const RunnerPongData& v)
{
    return v.Hash();
}

// RunnerSystemInfoData

RunnerSystemInfoData::RunnerSystemInfoData(
    const std::string& runner,
    const std::string& version,
    const std::string& wayland_display,
    int64_t width,
    int64_t height,
    double pixel_ratio,
    bool fullscreen,
    bool maximized,
    const std::string& title,
    const std::string& app_id) :
    runner_(runner),
    version_(version),
    wayland_display_(wayland_display),
    width_(width),
    height_(height),
    pixel_ratio_(pixel_ratio),
    fullscreen_(fullscreen),
    maximized_(maximized),
    title_(title),
    app_id_(app_id)
{}

const std::string& RunnerSystemInfoData::runner() const
{
    return runner_;
}

void RunnerSystemInfoData::set_runner(std::string_view value_arg)
{
    runner_ = value_arg;
}

const std::string& RunnerSystemInfoData::version() const
{
    return version_;
}

void RunnerSystemInfoData::set_version(std::string_view value_arg)
{
    version_ = value_arg;
}

const std::string& RunnerSystemInfoData::wayland_display() const
{
    return wayland_display_;
}

void RunnerSystemInfoData::set_wayland_display(std::string_view value_arg)
{
    wayland_display_ = value_arg;
}

int64_t RunnerSystemInfoData::width() const
{
    return width_;
}

void RunnerSystemInfoData::set_width(int64_t value_arg)
{
    width_ = value_arg;
}

int64_t RunnerSystemInfoData::height() const
{
    return height_;
}

void RunnerSystemInfoData::set_height(int64_t value_arg)
{
    height_ = value_arg;
}

double RunnerSystemInfoData::pixel_ratio() const
{
    return pixel_ratio_;
}

void RunnerSystemInfoData::set_pixel_ratio(double value_arg)
{
    pixel_ratio_ = value_arg;
}

bool RunnerSystemInfoData::fullscreen() const
{
    return fullscreen_;
}

void RunnerSystemInfoData::set_fullscreen(bool value_arg)
{
    fullscreen_ = value_arg;
}

bool RunnerSystemInfoData::maximized() const
{
    return maximized_;
}

void RunnerSystemInfoData::set_maximized(bool value_arg)
{
    maximized_ = value_arg;
}

const std::string& RunnerSystemInfoData::title() const
{
    return title_;
}

void RunnerSystemInfoData::set_title(std::string_view value_arg)
{
    title_ = value_arg;
}

const std::string& RunnerSystemInfoData::app_id() const
{
    return app_id_;
}

void RunnerSystemInfoData::set_app_id(std::string_view value_arg)
{
    app_id_ = value_arg;
}

EncodableList RunnerSystemInfoData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(10);
    list.push_back(EncodableValue(runner_));
    list.push_back(EncodableValue(version_));
    list.push_back(EncodableValue(wayland_display_));
    list.push_back(EncodableValue(width_));
    list.push_back(EncodableValue(height_));
    list.push_back(EncodableValue(pixel_ratio_));
    list.push_back(EncodableValue(fullscreen_));
    list.push_back(EncodableValue(maximized_));
    list.push_back(EncodableValue(title_));
    list.push_back(EncodableValue(app_id_));
    return list;
}

RunnerSystemInfoData RunnerSystemInfoData::FromEncodableList(const EncodableList& list)
{
    RunnerSystemInfoData decoded(
        std::get<std::string>(list[0]),
        std::get<std::string>(list[1]),
        std::get<std::string>(list[2]),
        std::get<int64_t>(list[3]),
        std::get<int64_t>(list[4]),
        std::get<double>(list[5]),
        std::get<bool>(list[6]),
        std::get<bool>(list[7]),
        std::get<std::string>(list[8]),
        std::get<std::string>(list[9]));
    return decoded;
}

bool RunnerSystemInfoData::operator ==(const RunnerSystemInfoData& other) const
{
    return PigeonInternalDeepEquals(runner_, other.runner_) && PigeonInternalDeepEquals(version_,
        other.version_) && PigeonInternalDeepEquals(wayland_display_,
        other.wayland_display_) && PigeonInternalDeepEquals(width_,
        other.width_) && PigeonInternalDeepEquals(height_,
        other.height_) && PigeonInternalDeepEquals(pixel_ratio_,
        other.pixel_ratio_) && PigeonInternalDeepEquals(fullscreen_,
        other.fullscreen_) && PigeonInternalDeepEquals(maximized_,
        other.maximized_) && PigeonInternalDeepEquals(title_,
        other.title_) && PigeonInternalDeepEquals(app_id_, other.app_id_);
}

bool RunnerSystemInfoData::operator !=(const RunnerSystemInfoData& other) const
{
    return !(*this == other);
}

size_t RunnerSystemInfoData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(runner_);
    result = result * 31 + PigeonInternalDeepHash(version_);
    result = result * 31 + PigeonInternalDeepHash(wayland_display_);
    result = result * 31 + PigeonInternalDeepHash(width_);
    result = result * 31 + PigeonInternalDeepHash(height_);
    result = result * 31 + PigeonInternalDeepHash(pixel_ratio_);
    result = result * 31 + PigeonInternalDeepHash(fullscreen_);
    result = result * 31 + PigeonInternalDeepHash(maximized_);
    result = result * 31 + PigeonInternalDeepHash(title_);
    result = result * 31 + PigeonInternalDeepHash(app_id_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const RunnerSystemInfoData& obj)
{
    os << "RunnerSystemInfoData(";
    os << "runner: ";
    os << PigeonInternalToString(obj.runner_);
    os << ", version: ";
    os << PigeonInternalToString(obj.version_);
    os << ", wayland_display: ";
    os << PigeonInternalToString(obj.wayland_display_);
    os << ", width: ";
    os << PigeonInternalToString(obj.width_);
    os << ", height: ";
    os << PigeonInternalToString(obj.height_);
    os << ", pixel_ratio: ";
    os << PigeonInternalToString(obj.pixel_ratio_);
    os << ", fullscreen: ";
    os << PigeonInternalToString(obj.fullscreen_);
    os << ", maximized: ";
    os << PigeonInternalToString(obj.maximized_);
    os << ", title: ";
    os << PigeonInternalToString(obj.title_);
    os << ", app_id: ";
    os << PigeonInternalToString(obj.app_id_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const RunnerSystemInfoData& v)
{
    return v.Hash();
}

// CompositorPongData

CompositorPongData::CompositorPongData(
    bool pong,
    int64_t timestamp_us,
    int64_t peer_pid) :
    pong_(pong),
    timestamp_us_(timestamp_us),
    peer_pid_(peer_pid)
{}

bool CompositorPongData::pong() const
{
    return pong_;
}

void CompositorPongData::set_pong(bool value_arg)
{
    pong_ = value_arg;
}

int64_t CompositorPongData::timestamp_us() const
{
    return timestamp_us_;
}

void CompositorPongData::set_timestamp_us(int64_t value_arg)
{
    timestamp_us_ = value_arg;
}

int64_t CompositorPongData::peer_pid() const
{
    return peer_pid_;
}

void CompositorPongData::set_peer_pid(int64_t value_arg)
{
    peer_pid_ = value_arg;
}

EncodableList CompositorPongData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(3);
    list.push_back(EncodableValue(pong_));
    list.push_back(EncodableValue(timestamp_us_));
    list.push_back(EncodableValue(peer_pid_));
    return list;
}

CompositorPongData CompositorPongData::FromEncodableList(const EncodableList& list)
{
    CompositorPongData decoded(
        std::get<bool>(list[0]),
        std::get<int64_t>(list[1]),
        std::get<int64_t>(list[2]));
    return decoded;
}

bool CompositorPongData::operator ==(const CompositorPongData& other) const
{
    return PigeonInternalDeepEquals(pong_, other.pong_) && PigeonInternalDeepEquals(timestamp_us_,
        other.timestamp_us_) && PigeonInternalDeepEquals(peer_pid_, other.peer_pid_);
}

bool CompositorPongData::operator !=(const CompositorPongData& other) const
{
    return !(*this == other);
}

size_t CompositorPongData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(pong_);
    result = result * 31 + PigeonInternalDeepHash(timestamp_us_);
    result = result * 31 + PigeonInternalDeepHash(peer_pid_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const CompositorPongData& obj)
{
    os << "CompositorPongData(";
    os << "pong: ";
    os << PigeonInternalToString(obj.pong_);
    os << ", timestamp_us: ";
    os << PigeonInternalToString(obj.timestamp_us_);
    os << ", peer_pid: ";
    os << PigeonInternalToString(obj.peer_pid_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const CompositorPongData& v)
{
    return v.Hash();
}

// CompositorSystemInfoData

CompositorSystemInfoData::CompositorSystemInfoData(
    const std::string& compositor,
    const std::string& version,
    const std::string& ipc_channel,
    int64_t surfaces_count,
    double client_fps,
    int64_t peer_pid,
    const std::string& app_id) :
    compositor_(compositor),
    version_(version),
    ipc_channel_(ipc_channel),
    surfaces_count_(surfaces_count),
    client_fps_(client_fps),
    peer_pid_(peer_pid),
    app_id_(app_id)
{}

const std::string& CompositorSystemInfoData::compositor() const
{
    return compositor_;
}

void CompositorSystemInfoData::set_compositor(std::string_view value_arg)
{
    compositor_ = value_arg;
}

const std::string& CompositorSystemInfoData::version() const
{
    return version_;
}

void CompositorSystemInfoData::set_version(std::string_view value_arg)
{
    version_ = value_arg;
}

const std::string& CompositorSystemInfoData::ipc_channel() const
{
    return ipc_channel_;
}

void CompositorSystemInfoData::set_ipc_channel(std::string_view value_arg)
{
    ipc_channel_ = value_arg;
}

int64_t CompositorSystemInfoData::surfaces_count() const
{
    return surfaces_count_;
}

void CompositorSystemInfoData::set_surfaces_count(int64_t value_arg)
{
    surfaces_count_ = value_arg;
}

double CompositorSystemInfoData::client_fps() const
{
    return client_fps_;
}

void CompositorSystemInfoData::set_client_fps(double value_arg)
{
    client_fps_ = value_arg;
}

int64_t CompositorSystemInfoData::peer_pid() const
{
    return peer_pid_;
}

void CompositorSystemInfoData::set_peer_pid(int64_t value_arg)
{
    peer_pid_ = value_arg;
}

const std::string& CompositorSystemInfoData::app_id() const
{
    return app_id_;
}

void CompositorSystemInfoData::set_app_id(std::string_view value_arg)
{
    app_id_ = value_arg;
}

EncodableList CompositorSystemInfoData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(7);
    list.push_back(EncodableValue(compositor_));
    list.push_back(EncodableValue(version_));
    list.push_back(EncodableValue(ipc_channel_));
    list.push_back(EncodableValue(surfaces_count_));
    list.push_back(EncodableValue(client_fps_));
    list.push_back(EncodableValue(peer_pid_));
    list.push_back(EncodableValue(app_id_));
    return list;
}

CompositorSystemInfoData CompositorSystemInfoData::FromEncodableList(const EncodableList& list)
{
    CompositorSystemInfoData decoded(
        std::get<std::string>(list[0]),
        std::get<std::string>(list[1]),
        std::get<std::string>(list[2]),
        std::get<int64_t>(list[3]),
        std::get<double>(list[4]),
        std::get<int64_t>(list[5]),
        std::get<std::string>(list[6]));
    return decoded;
}

bool CompositorSystemInfoData::operator ==(const CompositorSystemInfoData& other) const
{
    return PigeonInternalDeepEquals(compositor_, other.compositor_) && PigeonInternalDeepEquals(version_,
        other.version_) && PigeonInternalDeepEquals(ipc_channel_,
        other.ipc_channel_) && PigeonInternalDeepEquals(surfaces_count_,
        other.surfaces_count_) && PigeonInternalDeepEquals(client_fps_,
        other.client_fps_) && PigeonInternalDeepEquals(peer_pid_,
        other.peer_pid_) && PigeonInternalDeepEquals(app_id_, other.app_id_);
}

bool CompositorSystemInfoData::operator !=(const CompositorSystemInfoData& other) const
{
    return !(*this == other);
}

size_t CompositorSystemInfoData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(compositor_);
    result = result * 31 + PigeonInternalDeepHash(version_);
    result = result * 31 + PigeonInternalDeepHash(ipc_channel_);
    result = result * 31 + PigeonInternalDeepHash(surfaces_count_);
    result = result * 31 + PigeonInternalDeepHash(client_fps_);
    result = result * 31 + PigeonInternalDeepHash(peer_pid_);
    result = result * 31 + PigeonInternalDeepHash(app_id_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const CompositorSystemInfoData& obj)
{
    os << "CompositorSystemInfoData(";
    os << "compositor: ";
    os << PigeonInternalToString(obj.compositor_);
    os << ", version: ";
    os << PigeonInternalToString(obj.version_);
    os << ", ipc_channel: ";
    os << PigeonInternalToString(obj.ipc_channel_);
    os << ", surfaces_count: ";
    os << PigeonInternalToString(obj.surfaces_count_);
    os << ", client_fps: ";
    os << PigeonInternalToString(obj.client_fps_);
    os << ", peer_pid: ";
    os << PigeonInternalToString(obj.peer_pid_);
    os << ", app_id: ";
    os << PigeonInternalToString(obj.app_id_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const CompositorSystemInfoData& v)
{
    return v.Hash();
}

// CompositorSurfaceData

CompositorSurfaceData::CompositorSurfaceData(
    const std::string& title,
    int64_t handle,
    const std::string& app_id,
    int64_t width,
    int64_t height,
    bool fullscreen,
    bool maximized,
    bool activated) :
    title_(title),
    handle_(handle),
    app_id_(app_id),
    width_(width),
    height_(height),
    fullscreen_(fullscreen),
    maximized_(maximized),
    activated_(activated)
{}

const std::string& CompositorSurfaceData::title() const
{
    return title_;
}

void CompositorSurfaceData::set_title(std::string_view value_arg)
{
    title_ = value_arg;
}

int64_t CompositorSurfaceData::handle() const
{
    return handle_;
}

void CompositorSurfaceData::set_handle(int64_t value_arg)
{
    handle_ = value_arg;
}

const std::string& CompositorSurfaceData::app_id() const
{
    return app_id_;
}

void CompositorSurfaceData::set_app_id(std::string_view value_arg)
{
    app_id_ = value_arg;
}

int64_t CompositorSurfaceData::width() const
{
    return width_;
}

void CompositorSurfaceData::set_width(int64_t value_arg)
{
    width_ = value_arg;
}

int64_t CompositorSurfaceData::height() const
{
    return height_;
}

void CompositorSurfaceData::set_height(int64_t value_arg)
{
    height_ = value_arg;
}

bool CompositorSurfaceData::fullscreen() const
{
    return fullscreen_;
}

void CompositorSurfaceData::set_fullscreen(bool value_arg)
{
    fullscreen_ = value_arg;
}

bool CompositorSurfaceData::maximized() const
{
    return maximized_;
}

void CompositorSurfaceData::set_maximized(bool value_arg)
{
    maximized_ = value_arg;
}

bool CompositorSurfaceData::activated() const
{
    return activated_;
}

void CompositorSurfaceData::set_activated(bool value_arg)
{
    activated_ = value_arg;
}

EncodableList CompositorSurfaceData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(8);
    list.push_back(EncodableValue(title_));
    list.push_back(EncodableValue(handle_));
    list.push_back(EncodableValue(app_id_));
    list.push_back(EncodableValue(width_));
    list.push_back(EncodableValue(height_));
    list.push_back(EncodableValue(fullscreen_));
    list.push_back(EncodableValue(maximized_));
    list.push_back(EncodableValue(activated_));
    return list;
}

CompositorSurfaceData CompositorSurfaceData::FromEncodableList(const EncodableList& list)
{
    CompositorSurfaceData decoded(
        std::get<std::string>(list[0]),
        std::get<int64_t>(list[1]),
        std::get<std::string>(list[2]),
        std::get<int64_t>(list[3]),
        std::get<int64_t>(list[4]),
        std::get<bool>(list[5]),
        std::get<bool>(list[6]),
        std::get<bool>(list[7]));
    return decoded;
}

bool CompositorSurfaceData::operator ==(const CompositorSurfaceData& other) const
{
    return PigeonInternalDeepEquals(title_, other.title_) && PigeonInternalDeepEquals(handle_,
        other.handle_) && PigeonInternalDeepEquals(app_id_, other.app_id_) && PigeonInternalDeepEquals(width_,
        other.width_) && PigeonInternalDeepEquals(height_,
        other.height_) && PigeonInternalDeepEquals(fullscreen_,
        other.fullscreen_) && PigeonInternalDeepEquals(maximized_,
        other.maximized_) && PigeonInternalDeepEquals(activated_, other.activated_);
}

bool CompositorSurfaceData::operator !=(const CompositorSurfaceData& other) const
{
    return !(*this == other);
}

size_t CompositorSurfaceData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(title_);
    result = result * 31 + PigeonInternalDeepHash(handle_);
    result = result * 31 + PigeonInternalDeepHash(app_id_);
    result = result * 31 + PigeonInternalDeepHash(width_);
    result = result * 31 + PigeonInternalDeepHash(height_);
    result = result * 31 + PigeonInternalDeepHash(fullscreen_);
    result = result * 31 + PigeonInternalDeepHash(maximized_);
    result = result * 31 + PigeonInternalDeepHash(activated_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const CompositorSurfaceData& obj)
{
    os << "CompositorSurfaceData(";
    os << "title: ";
    os << PigeonInternalToString(obj.title_);
    os << ", handle: ";
    os << PigeonInternalToString(obj.handle_);
    os << ", app_id: ";
    os << PigeonInternalToString(obj.app_id_);
    os << ", width: ";
    os << PigeonInternalToString(obj.width_);
    os << ", height: ";
    os << PigeonInternalToString(obj.height_);
    os << ", fullscreen: ";
    os << PigeonInternalToString(obj.fullscreen_);
    os << ", maximized: ";
    os << PigeonInternalToString(obj.maximized_);
    os << ", activated: ";
    os << PigeonInternalToString(obj.activated_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const CompositorSurfaceData& v)
{
    return v.Hash();
}

PigeonInternalCodecSerializer::PigeonInternalCodecSerializer()
{}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader *stream) const
{
    switch (type)
    {
      case 129:
    {
        return CustomEncodableValue(RunnerPongData::FromEncodableList(std::get<EncodableList>(ReadValue(
            stream))));
    }

      case 130:
    {
        return CustomEncodableValue(RunnerSystemInfoData::FromEncodableList(std::get<EncodableList>(ReadValue(
            stream))));
    }

      case 131:
    {
        return CustomEncodableValue(CompositorPongData::FromEncodableList(std::get<EncodableList>(ReadValue(
            stream))));
    }

      case 132:
    {
        return CustomEncodableValue(CompositorSystemInfoData::FromEncodableList(std::get<EncodableList>(
            ReadValue(stream))));
    }

      case 133:
    {
        return CustomEncodableValue(CompositorSurfaceData::FromEncodableList(std::get<EncodableList>(
            ReadValue(stream))));
    }

      default:
        return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
    const EncodableValue& value,
    ::flutter::ByteStreamWriter *stream) const
{
    if (const CustomEncodableValue *custom_value = std::get_if<CustomEncodableValue>(&value))
    {
        if (custom_value->type() == typeid(RunnerPongData))
        {
            stream->WriteByte(129);
            WriteValue(EncodableValue(std::any_cast<RunnerPongData>(*custom_value).ToEncodableList()),
                stream);
            return;
        }

        if (custom_value->type() == typeid(RunnerSystemInfoData))
        {
            stream->WriteByte(130);
            WriteValue(EncodableValue(std::any_cast<RunnerSystemInfoData>(*custom_value).ToEncodableList()),
                stream);
            return;
        }

        if (custom_value->type() == typeid(CompositorPongData))
        {
            stream->WriteByte(131);
            WriteValue(EncodableValue(std::any_cast<CompositorPongData>(*custom_value).ToEncodableList()),
                stream);
            return;
        }

        if (custom_value->type() == typeid(CompositorSystemInfoData))
        {
            stream->WriteByte(132);
            WriteValue(EncodableValue(std::any_cast<CompositorSystemInfoData>(
                *custom_value).ToEncodableList()), stream);
            return;
        }

        if (custom_value->type() == typeid(CompositorSurfaceData))
        {
            stream->WriteByte(133);
            WriteValue(EncodableValue(std::any_cast<CompositorSurfaceData>(*custom_value).ToEncodableList()),
                stream);
            return;
        }
    }

    ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by RunnerHostApi.
const ::flutter::StandardMessageCodec& RunnerHostApi::GetCodec()
{
    return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `RunnerHostApi` to handle messages through the `binary_messenger`.
void RunnerHostApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    RunnerHostApi *api)
{
    RunnerHostApi::SetUp(binary_messenger, api, "");
}

void RunnerHostApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    RunnerHostApi *api,
    const std::string& message_channel_suffix)
{
    const std::string prepended_suffix = message_channel_suffix.length() >
        0 ? std::string(".") + message_channel_suffix : "";
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.getSystemInfo" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->GetSystemInfo([reply] (ErrorOr<std::optional<RunnerSystemInfoData>>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        auto output_optional = std::move(output).TakeValue();
                        if (output_optional)
                        {
                            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
                        } else
                        {
                            wrapped.push_back(EncodableValue());
                        }

                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setWindowTitle" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_title_arg = args.at(0);
                    if (encodable_title_arg.IsNull())
                    {
                        reply(WrapError("title_arg unexpectedly null."));
                        return;
                    }

                    const auto& title_arg = std::get<std::string>(encodable_title_arg);
                    api->SetWindowTitle(title_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setFullscreen" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_enabled_arg = args.at(0);
                    if (encodable_enabled_arg.IsNull())
                    {
                        reply(WrapError("enabled_arg unexpectedly null."));
                        return;
                    }

                    const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
                    api->SetFullscreen(enabled_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.setMaximized" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_enabled_arg = args.at(0);
                    if (encodable_enabled_arg.IsNull())
                    {
                        reply(WrapError("enabled_arg unexpectedly null."));
                        return;
                    }

                    const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
                    api->SetMaximized(enabled_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.minimize" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->Minimize([reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostApi.ping" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->Ping([reply] (ErrorOr<RunnerPongData>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
}

EncodableValue RunnerHostApi::WrapError(std::string_view error_message)
{
    return EncodableValue(EncodableList{
            EncodableValue(std::string(error_message)),
            EncodableValue("Error"),
            EncodableValue()
        });
}

EncodableValue RunnerHostApi::WrapError(const FlutterError& error)
{
    return EncodableValue(EncodableList{
            EncodableValue(error.code()),
            EncodableValue(error.message()),
            error.details()
        });
}

/// The codec used by RunnerHostIpcApi.
const ::flutter::StandardMessageCodec& RunnerHostIpcApi::GetCodec()
{
    return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `RunnerHostIpcApi` to handle messages through the `binary_messenger`.
void RunnerHostIpcApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    RunnerHostIpcApi *api)
{
    RunnerHostIpcApi::SetUp(binary_messenger, api, "");
}

void RunnerHostIpcApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    RunnerHostIpcApi *api,
    const std::string& message_channel_suffix)
{
    const std::string prepended_suffix = message_channel_suffix.length() >
        0 ? std::string(".") + message_channel_suffix : "";
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.getCompositorInfo" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->GetCompositorInfo([reply] (ErrorOr<std::optional<CompositorSystemInfoData>>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        auto output_optional = std::move(output).TakeValue();
                        if (output_optional)
                        {
                            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
                        } else
                        {
                            wrapped.push_back(EncodableValue());
                        }

                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.pingCompositor" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->PingCompositor([reply] (ErrorOr<std::optional<CompositorPongData>>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        auto output_optional = std::move(output).TakeValue();
                        if (output_optional)
                        {
                            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
                        } else
                        {
                            wrapped.push_back(EncodableValue());
                        }

                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.listSurfaces" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->ListSurfaces([reply] (ErrorOr<std::optional<EncodableList>>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        auto output_optional = std::move(output).TakeValue();
                        if (output_optional)
                        {
                            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
                        } else
                        {
                            wrapped.push_back(EncodableValue());
                        }

                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_runner.RunnerHostIpcApi.closeSurface" + prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    api->CloseSurface(surface_handle_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
}

EncodableValue RunnerHostIpcApi::WrapError(std::string_view error_message)
{
    return EncodableValue(EncodableList{
            EncodableValue(std::string(error_message)),
            EncodableValue("Error"),
            EncodableValue()
        });
}

EncodableValue RunnerHostIpcApi::WrapError(const FlutterError& error)
{
    return EncodableValue(EncodableList{
            EncodableValue(error.code()),
            EncodableValue(error.message()),
            error.details()
        });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
RunnerFlutterIpcApi::RunnerFlutterIpcApi(::flutter::BinaryMessenger *binary_messenger) :
    binary_messenger_(binary_messenger),
    message_channel_suffix_("")
{}

RunnerFlutterIpcApi::RunnerFlutterIpcApi(
    ::flutter::BinaryMessenger *binary_messenger,
    const std::string& message_channel_suffix) :
    binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() >
        0 ? std::string(".") + message_channel_suffix : "")
{}

const ::flutter::StandardMessageCodec& RunnerFlutterIpcApi::GetCodec()
{
    return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void RunnerFlutterIpcApi::OnNotification(
    const std::string& method_arg,
    const std::string *params_json_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_runner.RunnerFlutterIpcApi.onNotification" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(method_arg),
            params_json_arg ? EncodableValue(*params_json_arg) : EncodableValue(),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}
} // namespace sparrow
