// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace sparrow {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class CompositorHostApi;
  friend class CompositorFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class CompositorSocketsData {
 public:
  // Constructs an object setting all fields.
  explicit CompositorSocketsData(
    const std::string& wayland,
    const std::string& x);

  const std::string& wayland() const;
  void set_wayland(std::string_view value_arg);

  const std::string& x() const;
  void set_x(std::string_view value_arg);

  bool operator==(const CompositorSocketsData& other) const;
  bool operator!=(const CompositorSocketsData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const CompositorSocketsData& obj);
 private:
  static CompositorSocketsData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class CompositorHostApi;
  friend class CompositorFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string wayland_;
  std::string x_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class CompositorHostApi {
 public:
  CompositorHostApi(const CompositorHostApi&) = delete;
  CompositorHostApi& operator=(const CompositorHostApi&) = delete;
  virtual ~CompositorHostApi() {}
  virtual void SurfaceRequestResize(
    int64_t surface_handle,
    int64_t width,
    int64_t height,
    int64_t request_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceEndResize(
    int64_t surface_handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceToplevelSetSize(
    int64_t surface_handle,
    int64_t width,
    int64_t height,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceToplevelSetMaximized(
    int64_t surface_handle,
    bool maximized,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceToplevelClose(
    int64_t surface_handle,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SurfaceFocus(
    int64_t surface_handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceClearFocus(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfaceSetPosition(
    int64_t surface_handle,
    int64_t x,
    int64_t y,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ForceRenderAllViews(
    bool force,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetDirectInputMode(
    int64_t surface_handle,
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetPrimaryOutput(
    int64_t output_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetVsyncOutput(
    int64_t output_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetVsyncRateLimit(
    int64_t max_hz,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetOutputMode(
    int64_t output_id,
    int64_t width,
    int64_t height,
    int64_t refresh,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetOutputPosition(
    int64_t output_id,
    int64_t x,
    int64_t y,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetOutputScale(
    int64_t output_id,
    double scale,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void DebugSetDamageVisualization(
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void DebugGetDamageVisualization(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetSocketPaths(std::function<void(ErrorOr<CompositorSocketsData> reply)> result) = 0;
  virtual void CompositorReady(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void IsCompositor(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SurfaceKeyboardKey(
    int64_t surface_handle,
    int64_t keycode,
    int64_t status,
    int64_t timestamp_micros,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SurfacePointerEvent(
    const ::flutter::EncodableList& data,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void PopupPointerEvent(
    const ::flutter::EncodableList& data,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by CompositorHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `CompositorHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CompositorHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CompositorHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  CompositorHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class CompositorFlutterApi {
 public:
  CompositorFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  CompositorFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void SurfaceMap(
    const ::flutter::EncodableMap& surface,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SurfaceUnmap(
    int64_t handle,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SurfaceTitle(
    int64_t handle,
    const std::string& title,
    const std::string& app_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SurfaceGeometry(
    int64_t handle,
    int64_t width,
    int64_t height,
    int64_t buffer_width,
    int64_t buffer_height,
    int64_t geo_x,
    int64_t geo_y,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Pigeon requires positional arguments for FlutterApi methods.
  void SurfaceDecoration(
    int64_t handle,
    bool uses_ssd,
    bool uses_csd,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SurfaceMinimize(
    int64_t handle,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SurfaceRequestActivate(
    int64_t handle,
    const std::string& token,
    const std::string& app_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void ResizeReady(
    int64_t handle,
    int64_t request_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SubsurfaceMap(
    const ::flutter::EncodableMap& subsurface,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SubsurfaceUnmap(
    int64_t handle,
    int64_t parent_handle,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void SubsurfacePosition(
    int64_t handle,
    int64_t parent_handle,
    int64_t x,
    int64_t y,
    int64_t width,
    int64_t height,
    int64_t buffer_width,
    int64_t buffer_height,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void PopupMap(
    const ::flutter::EncodableMap& popup,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void PopupUnmap(
    int64_t handle,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OutputAdded(
    const ::flutter::EncodableMap& output,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OutputRemoved(
    int64_t output_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OutputChanged(
    const ::flutter::EncodableMap& output,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void GestureSwipeBegin(
    int64_t fingers,
    int64_t time_msec,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void GestureSwipeUpdate(
    double dx,
    double dy,
    int64_t time_msec,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Pigeon requires positional arguments for FlutterApi methods.
  void GestureSwipeEnd(
    bool cancelled,
    int64_t time_msec,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void ZoomScroll(
    double delta,
    double x,
    double y,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void ZoomKey(
    int64_t action,
    double x,
    double y,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace sparrow
#endif  // PIGEON_MESSAGES_G_H_
