// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace sparrow
{
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name)
{
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

namespace
{
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b)
{
    return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b)
{
    if (a.size() != b.size())
    {
        return false;
    }

    for (size_t i = 0; i < a.size(); ++i)
    {
        if (!PigeonInternalDeepEquals(a[i], b[i]))
        {
            return false;
        }
    }

    return true;
}

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b)
{
    if (a.size() != b.size())
    {
        return false;
    }

    for (const auto& kv : a)
    {
        bool found = false;
        for (const auto& b_kv : b)
        {
            if (PigeonInternalDeepEquals(kv.first, b_kv.first))
            {
                if (PigeonInternalDeepEquals(kv.second, b_kv.second))
                {
                    found = true;
                    break;
                } else
                {
                    return false;
                }
            }
        }

        if (!found)
        {
            return false;
        }
    }

    return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b)
{
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b)
{
    if (!a && !b)
    {
        return true;
    }

    if (!a || !b)
    {
        return false;
    }

    return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b)
{
    if (a.get() == b.get())
    {
        return true;
    }

    if (!a || !b)
    {
        return false;
    }

    return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b)
{
    if (a.index() != b.index())
    {
        return false;
    }

    if (const double *da = std::get_if<double>(&a))
    {
        return PigeonInternalDeepEquals(*da, std::get<double>(b));
    } else if (const ::flutter::EncodableList *la = std::get_if<::flutter::EncodableList>(&a))
    {
        return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
    } else if (const ::flutter::EncodableMap *ma = std::get_if<::flutter::EncodableMap>(&a))
    {
        return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
    }

    return a == b;
}

template<typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template<typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template<typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template<typename T>
size_t PigeonInternalDeepHash(const T& v)
{
    return std::hash<T>()(v);
}

template<typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v)
{
    size_t result = 1;
    for (const auto& item : v)
    {
        result = result * 31 + PigeonInternalDeepHash(item);
    }

    return result;
}

template<typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v)
{
    size_t result = 0;
    for (const auto& kv : v)
    {
        result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
    }

    return result;
}

size_t PigeonInternalDeepHash(const double& v)
{
    if (std::isnan(v))
    {
        // Normalize NaN to a consistent hash.
        return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
    }

    if (v == 0.0)
    {
        // Normalize -0.0 to 0.0 so they have the same hash code.
        return std::hash<double>()(0.0);
    }

    return std::hash<double>()(v);
}

template<typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v)
{
    return v ? PigeonInternalDeepHash(*v) : 0;
}

template<typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v)
{
    return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v)
{
    size_t result = v.index();
    if (const double *dv = std::get_if<double>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*dv);
    } else if (const ::flutter::EncodableList *lv =
                   std::get_if<::flutter::EncodableList>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*lv);
    } else if (const ::flutter::EncodableMap *mv =
                   std::get_if<::flutter::EncodableMap>(&v))
    {
        result = result * 31 + PigeonInternalDeepHash(*mv);
    } else
    {
        std::visit(
            [&result] (const auto& val)
        {
            using T = std::decay_t<decltype(val)>;
            if constexpr (!std::is_same_v<T, double> &&
                          !std::is_same_v<T, ::flutter::EncodableList> &&
                          !std::is_same_v<T, ::flutter::EncodableMap> &&
                          !std::is_same_v<T, std::monostate> &&
                          !std::is_same_v<T, ::flutter::CustomEncodableValue> )
            {
                result = result * 31 + PigeonInternalDeepHash(val);
            }
        },
            v);
    }

    return result;
}

template<typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template<typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template<typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template<typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template<typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template<typename T>
std::string PigeonInternalToString(const T& v)
{
    std::stringstream ss;
    if constexpr (std::is_enum_v<T> )
    {
        ss << static_cast<int>(v);
    } else
    {
        ss << v;
    }

    return ss.str();
}

std::string PigeonInternalToString(const bool& v)
{
    return v ? "true" : "false";
}

template<typename T>
std::string PigeonInternalToString(const std::vector<T>& v)
{
    std::stringstream ss;
    ss << "[";
    for (size_t i = 0; i < v.size(); ++i)
    {
        if (i > 0)
        {
            ss << ", ";
        }

        ss << PigeonInternalToString(v[i]);
    }

    ss << "]";
    return ss.str();
}

template<typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v)
{
    std::stringstream ss;
    ss << "{";
    bool first = true;
    for (const auto& kv : v)
    {
        if (!first)
        {
            ss << ", ";
        }

        first = false;
        ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
    }

    ss << "}";
    return ss.str();
}

template<typename T>
std::string PigeonInternalToString(const std::optional<T>& v)
{
    return v ? PigeonInternalToString(*v) : "null";
}

template<typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v)
{
    return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v)
{
    return std::visit(
        [] (const auto& val)
    {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate> )
        {
            return std::string("null");
        } else if constexpr (std::is_same_v<T, bool> )
        {
            return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string> )
        {
            return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue> )
        {
            return std::string("[custom]");
        } else
        {
            return PigeonInternalToString(val);
        }
    },
        v);
}
} // namespace

// CompositorSocketsData

CompositorSocketsData::CompositorSocketsData(
    const std::string& wayland,
    const std::string& x) :
    wayland_(wayland),
    x_(x)
{}

const std::string& CompositorSocketsData::wayland() const
{
    return wayland_;
}

void CompositorSocketsData::set_wayland(std::string_view value_arg)
{
    wayland_ = value_arg;
}

const std::string& CompositorSocketsData::x() const
{
    return x_;
}

void CompositorSocketsData::set_x(std::string_view value_arg)
{
    x_ = value_arg;
}

EncodableList CompositorSocketsData::ToEncodableList() const
{
    EncodableList list;
    list.reserve(2);
    list.push_back(EncodableValue(wayland_));
    list.push_back(EncodableValue(x_));
    return list;
}

CompositorSocketsData CompositorSocketsData::FromEncodableList(const EncodableList& list)
{
    CompositorSocketsData decoded(
        std::get<std::string>(list[0]),
        std::get<std::string>(list[1]));
    return decoded;
}

bool CompositorSocketsData::operator ==(const CompositorSocketsData& other) const
{
    return PigeonInternalDeepEquals(wayland_, other.wayland_) && PigeonInternalDeepEquals(x_, other.x_);
}

bool CompositorSocketsData::operator !=(const CompositorSocketsData& other) const
{
    return !(*this == other);
}

size_t CompositorSocketsData::Hash() const
{
    size_t result = 1;
    result = result * 31 + PigeonInternalDeepHash(wayland_);
    result = result * 31 + PigeonInternalDeepHash(x_);
    return result;
}

std::ostream& operator <<(
    std::ostream& os,
    const CompositorSocketsData& obj)
{
    os << "CompositorSocketsData(";
    os << "wayland: ";
    os << PigeonInternalToString(obj.wayland_);
    os << ", x: ";
    os << PigeonInternalToString(obj.x_);
    os << ")";
    return os;
}

size_t PigeonInternalDeepHash(const CompositorSocketsData& v)
{
    return v.Hash();
}

PigeonInternalCodecSerializer::PigeonInternalCodecSerializer()
{}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader *stream) const
{
    switch (type)
    {
      case 129:
    {
        return CustomEncodableValue(CompositorSocketsData::FromEncodableList(std::get<EncodableList>(
            ReadValue(stream))));
    }

      default:
        return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
    const EncodableValue& value,
    ::flutter::ByteStreamWriter *stream) const
{
    if (const CustomEncodableValue *custom_value = std::get_if<CustomEncodableValue>(&value))
    {
        if (custom_value->type() == typeid(CompositorSocketsData))
        {
            stream->WriteByte(129);
            WriteValue(EncodableValue(std::any_cast<CompositorSocketsData>(*custom_value).ToEncodableList()),
                stream);
            return;
        }
    }

    ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by CompositorHostApi.
const ::flutter::StandardMessageCodec& CompositorHostApi::GetCodec()
{
    return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `CompositorHostApi` to handle messages through the `binary_messenger`.
void CompositorHostApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    CompositorHostApi *api)
{
    CompositorHostApi::SetUp(binary_messenger, api, "");
}

void CompositorHostApi::SetUp(
    ::flutter::BinaryMessenger *binary_messenger,
    CompositorHostApi *api,
    const std::string& message_channel_suffix)
{
    const std::string prepended_suffix = message_channel_suffix.length() >
        0 ? std::string(".") + message_channel_suffix : "";
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceRequestResize" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_width_arg  = args.at(1);
                    if (encodable_width_arg.IsNull())
                    {
                        reply(WrapError("width_arg unexpectedly null."));
                        return;
                    }

                    const int64_t width_arg = encodable_width_arg.LongValue();
                    const auto& encodable_height_arg = args.at(2);
                    if (encodable_height_arg.IsNull())
                    {
                        reply(WrapError("height_arg unexpectedly null."));
                        return;
                    }

                    const int64_t height_arg = encodable_height_arg.LongValue();
                    const auto& encodable_request_id_arg = args.at(3);
                    if (encodable_request_id_arg.IsNull())
                    {
                        reply(WrapError("request_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t request_id_arg = encodable_request_id_arg.LongValue();
                    api->SurfaceRequestResize(surface_handle_arg, width_arg, height_arg, request_id_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceEndResize" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    api->SurfaceEndResize(surface_handle_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceToplevelSetSize" +
            prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_width_arg  = args.at(1);
                    if (encodable_width_arg.IsNull())
                    {
                        reply(WrapError("width_arg unexpectedly null."));
                        return;
                    }

                    const int64_t width_arg = encodable_width_arg.LongValue();
                    const auto& encodable_height_arg = args.at(2);
                    if (encodable_height_arg.IsNull())
                    {
                        reply(WrapError("height_arg unexpectedly null."));
                        return;
                    }

                    const int64_t height_arg = encodable_height_arg.LongValue();
                    api->SurfaceToplevelSetSize(surface_handle_arg, width_arg, height_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceToplevelSetMaximized" +
            prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg    = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_maximized_arg = args.at(1);
                    if (encodable_maximized_arg.IsNull())
                    {
                        reply(WrapError("maximized_arg unexpectedly null."));
                        return;
                    }

                    const auto& maximized_arg = std::get<bool>(encodable_maximized_arg);
                    api->SurfaceToplevelSetMaximized(surface_handle_arg, maximized_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceToplevelClose" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    api->SurfaceToplevelClose(surface_handle_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceFocus" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    api->SurfaceFocus(surface_handle_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceClearFocus" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->SurfaceClearFocus([reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceSetPosition" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_x_arg = args.at(1);
                    if (encodable_x_arg.IsNull())
                    {
                        reply(WrapError("x_arg unexpectedly null."));
                        return;
                    }

                    const int64_t x_arg = encodable_x_arg.LongValue();
                    const auto& encodable_y_arg = args.at(2);
                    if (encodable_y_arg.IsNull())
                    {
                        reply(WrapError("y_arg unexpectedly null."));
                        return;
                    }

                    const int64_t y_arg = encodable_y_arg.LongValue();
                    api->SurfaceSetPosition(surface_handle_arg, x_arg, y_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.forceRenderAllViews" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_force_arg = args.at(0);
                    if (encodable_force_arg.IsNull())
                    {
                        reply(WrapError("force_arg unexpectedly null."));
                        return;
                    }

                    const auto& force_arg = std::get<bool>(encodable_force_arg);
                    api->ForceRenderAllViews(force_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setDirectInputMode" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg  = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_enabled_arg = args.at(1);
                    if (encodable_enabled_arg.IsNull())
                    {
                        reply(WrapError("enabled_arg unexpectedly null."));
                        return;
                    }

                    const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
                    api->SetDirectInputMode(surface_handle_arg, enabled_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setPrimaryOutput" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_output_id_arg = args.at(0);
                    if (encodable_output_id_arg.IsNull())
                    {
                        reply(WrapError("output_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t output_id_arg = encodable_output_id_arg.LongValue();
                    api->SetPrimaryOutput(output_id_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setVsyncOutput" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_output_id_arg = args.at(0);
                    if (encodable_output_id_arg.IsNull())
                    {
                        reply(WrapError("output_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t output_id_arg = encodable_output_id_arg.LongValue();
                    api->SetVsyncOutput(output_id_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setVsyncRateLimit" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_max_hz_arg = args.at(0);
                    if (encodable_max_hz_arg.IsNull())
                    {
                        reply(WrapError("max_hz_arg unexpectedly null."));
                        return;
                    }

                    const int64_t max_hz_arg = encodable_max_hz_arg.LongValue();
                    api->SetVsyncRateLimit(max_hz_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setOutputMode" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_output_id_arg = args.at(0);
                    if (encodable_output_id_arg.IsNull())
                    {
                        reply(WrapError("output_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t output_id_arg     = encodable_output_id_arg.LongValue();
                    const auto& encodable_width_arg = args.at(1);
                    if (encodable_width_arg.IsNull())
                    {
                        reply(WrapError("width_arg unexpectedly null."));
                        return;
                    }

                    const int64_t width_arg = encodable_width_arg.LongValue();
                    const auto& encodable_height_arg = args.at(2);
                    if (encodable_height_arg.IsNull())
                    {
                        reply(WrapError("height_arg unexpectedly null."));
                        return;
                    }

                    const int64_t height_arg = encodable_height_arg.LongValue();
                    const auto& encodable_refresh_arg = args.at(3);
                    if (encodable_refresh_arg.IsNull())
                    {
                        reply(WrapError("refresh_arg unexpectedly null."));
                        return;
                    }

                    const int64_t refresh_arg = encodable_refresh_arg.LongValue();
                    api->SetOutputMode(output_id_arg, width_arg, height_arg, refresh_arg,
                        [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setOutputPosition" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_output_id_arg = args.at(0);
                    if (encodable_output_id_arg.IsNull())
                    {
                        reply(WrapError("output_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t output_id_arg = encodable_output_id_arg.LongValue();
                    const auto& encodable_x_arg = args.at(1);
                    if (encodable_x_arg.IsNull())
                    {
                        reply(WrapError("x_arg unexpectedly null."));
                        return;
                    }

                    const int64_t x_arg = encodable_x_arg.LongValue();
                    const auto& encodable_y_arg = args.at(2);
                    if (encodable_y_arg.IsNull())
                    {
                        reply(WrapError("y_arg unexpectedly null."));
                        return;
                    }

                    const int64_t y_arg = encodable_y_arg.LongValue();
                    api->SetOutputPosition(output_id_arg, x_arg, y_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.setOutputScale" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_output_id_arg = args.at(0);
                    if (encodable_output_id_arg.IsNull())
                    {
                        reply(WrapError("output_id_arg unexpectedly null."));
                        return;
                    }

                    const int64_t output_id_arg     = encodable_output_id_arg.LongValue();
                    const auto& encodable_scale_arg = args.at(1);
                    if (encodable_scale_arg.IsNull())
                    {
                        reply(WrapError("scale_arg unexpectedly null."));
                        return;
                    }

                    const auto& scale_arg = std::get<double>(encodable_scale_arg);
                    api->SetOutputScale(output_id_arg, scale_arg, [reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.debugSetDamageVisualization" +
            prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_enabled_arg = args.at(0);
                    if (encodable_enabled_arg.IsNull())
                    {
                        reply(WrapError("enabled_arg unexpectedly null."));
                        return;
                    }

                    const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
                    api->DebugSetDamageVisualization(enabled_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.debugGetDamageVisualization" +
            prepended_suffix, &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->DebugGetDamageVisualization([reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.getSocketPaths" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->GetSocketPaths([reply] (ErrorOr<CompositorSocketsData>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.compositorReady" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->CompositorReady([reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.isCompositor" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    api->IsCompositor([reply] (ErrorOr<bool>&& output)
                    {
                        if (output.has_error())
                        {
                            reply(WrapError(output.error()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfaceKeyboardKey" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_surface_handle_arg = args.at(0);
                    if (encodable_surface_handle_arg.IsNull())
                    {
                        reply(WrapError("surface_handle_arg unexpectedly null."));
                        return;
                    }

                    const int64_t surface_handle_arg  = encodable_surface_handle_arg.LongValue();
                    const auto& encodable_keycode_arg = args.at(1);
                    if (encodable_keycode_arg.IsNull())
                    {
                        reply(WrapError("keycode_arg unexpectedly null."));
                        return;
                    }

                    const int64_t keycode_arg = encodable_keycode_arg.LongValue();
                    const auto& encodable_status_arg = args.at(2);
                    if (encodable_status_arg.IsNull())
                    {
                        reply(WrapError("status_arg unexpectedly null."));
                        return;
                    }

                    const int64_t status_arg = encodable_status_arg.LongValue();
                    const auto& encodable_timestamp_micros_arg = args.at(3);
                    if (encodable_timestamp_micros_arg.IsNull())
                    {
                        reply(WrapError("timestamp_micros_arg unexpectedly null."));
                        return;
                    }

                    const int64_t timestamp_micros_arg = encodable_timestamp_micros_arg.LongValue();
                    api->SurfaceKeyboardKey(surface_handle_arg, keycode_arg, status_arg, timestamp_micros_arg,
                        [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.surfacePointerEvent" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_data_arg = args.at(0);
                    if (encodable_data_arg.IsNull())
                    {
                        reply(WrapError("data_arg unexpectedly null."));
                        return;
                    }

                    const auto& data_arg = std::get<EncodableList>(encodable_data_arg);
                    api->SurfacePointerEvent(data_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
    {
        BasicMessageChannel<> channel(binary_messenger,
            "dev.flutter.pigeon.pigeon_compositor.CompositorHostApi.popupPointerEvent" + prepended_suffix,
            &GetCodec());
        if (api != nullptr)
        {
            channel.SetMessageHandler([api] (const EncodableValue& message,
                                             const ::flutter::MessageReply<EncodableValue>& reply)
            {
                try {
                    const auto& args = std::get<EncodableList>(message);
                    const auto& encodable_data_arg = args.at(0);
                    if (encodable_data_arg.IsNull())
                    {
                        reply(WrapError("data_arg unexpectedly null."));
                        return;
                    }

                    const auto& data_arg = std::get<EncodableList>(encodable_data_arg);
                    api->PopupPointerEvent(data_arg, [reply] (std::optional<FlutterError>&& output)
                    {
                        if (output.has_value())
                        {
                            reply(WrapError(output.value()));
                            return;
                        }

                        EncodableList wrapped;
                        wrapped.push_back(EncodableValue());
                        reply(EncodableValue(std::move(wrapped)));
                    });
                } catch (const std::exception& exception)
                {
                    reply(WrapError(exception.what()));
                }
            });
        } else
        {
            channel.SetMessageHandler(nullptr);
        }
    }
}

EncodableValue CompositorHostApi::WrapError(std::string_view error_message)
{
    return EncodableValue(EncodableList{
            EncodableValue(std::string(error_message)),
            EncodableValue("Error"),
            EncodableValue()
        });
}

EncodableValue CompositorHostApi::WrapError(const FlutterError& error)
{
    return EncodableValue(EncodableList{
            EncodableValue(error.code()),
            EncodableValue(error.message()),
            error.details()
        });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
CompositorFlutterApi::CompositorFlutterApi(::flutter::BinaryMessenger *binary_messenger) :
    binary_messenger_(binary_messenger),
    message_channel_suffix_("")
{}

CompositorFlutterApi::CompositorFlutterApi(
    ::flutter::BinaryMessenger *binary_messenger,
    const std::string& message_channel_suffix) :
    binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() >
        0 ? std::string(".") + message_channel_suffix : "")
{}

const ::flutter::StandardMessageCodec& CompositorFlutterApi::GetCodec()
{
    return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void CompositorFlutterApi::SurfaceMap(
    const EncodableMap& surface_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceMap" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(surface_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceUnmap(
    int64_t handle_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceUnmap" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceTitle(
    int64_t handle_arg,
    const std::string& title_arg,
    const std::string& app_id_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceTitle" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(title_arg),
            EncodableValue(app_id_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceGeometry(
    int64_t handle_arg,
    int64_t width_arg,
    int64_t height_arg,
    int64_t buffer_width_arg,
    int64_t buffer_height_arg,
    int64_t geo_x_arg,
    int64_t geo_y_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceGeometry" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(width_arg),
            EncodableValue(height_arg),
            EncodableValue(buffer_width_arg),
            EncodableValue(buffer_height_arg),
            EncodableValue(geo_x_arg),
            EncodableValue(geo_y_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceDecoration(
    int64_t handle_arg,
    bool uses_ssd_arg,
    bool uses_csd_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceDecoration" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(uses_ssd_arg),
            EncodableValue(uses_csd_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceMinimize(
    int64_t handle_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceMinimize" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SurfaceRequestActivate(
    int64_t handle_arg,
    const std::string& token_arg,
    const std::string& app_id_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.surfaceRequestActivate" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(token_arg),
            EncodableValue(app_id_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::ResizeReady(
    int64_t handle_arg,
    int64_t request_id_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.resizeReady" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(request_id_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SubsurfaceMap(
    const EncodableMap& subsurface_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.subsurfaceMap" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(subsurface_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SubsurfaceUnmap(
    int64_t handle_arg,
    int64_t parent_handle_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.subsurfaceUnmap" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(parent_handle_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::SubsurfacePosition(
    int64_t handle_arg,
    int64_t parent_handle_arg,
    int64_t x_arg,
    int64_t y_arg,
    int64_t width_arg,
    int64_t height_arg,
    int64_t buffer_width_arg,
    int64_t buffer_height_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.subsurfacePosition" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
            EncodableValue(parent_handle_arg),
            EncodableValue(x_arg),
            EncodableValue(y_arg),
            EncodableValue(width_arg),
            EncodableValue(height_arg),
            EncodableValue(buffer_width_arg),
            EncodableValue(buffer_height_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::PopupMap(
    const EncodableMap& popup_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.popupMap" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(popup_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::PopupUnmap(
    int64_t handle_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.popupUnmap" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(handle_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::OutputAdded(
    const EncodableMap& output_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.outputAdded" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(output_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::OutputRemoved(
    int64_t output_id_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.outputRemoved" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(output_id_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::OutputChanged(
    const EncodableMap& output_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.outputChanged" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(output_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::GestureSwipeBegin(
    int64_t fingers_arg,
    int64_t time_msec_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.gestureSwipeBegin" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(fingers_arg),
            EncodableValue(time_msec_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::GestureSwipeUpdate(
    double dx_arg,
    double dy_arg,
    int64_t time_msec_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.gestureSwipeUpdate" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(dx_arg),
            EncodableValue(dy_arg),
            EncodableValue(time_msec_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::GestureSwipeEnd(
    bool cancelled_arg,
    int64_t time_msec_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name =
        "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.gestureSwipeEnd" + message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(cancelled_arg),
            EncodableValue(time_msec_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::ZoomScroll(
    double delta_arg,
    double x_arg,
    double y_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.zoomScroll" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(delta_arg),
            EncodableValue(x_arg),
            EncodableValue(y_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}

void CompositorFlutterApi::ZoomKey(
    int64_t action_arg,
    double x_arg,
    double y_arg,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error)
{
    const std::string channel_name = "dev.flutter.pigeon.pigeon_compositor.CompositorFlutterApi.zoomKey" +
        message_channel_suffix_;
    BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
    EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
            EncodableValue(action_arg),
            EncodableValue(x_arg),
            EncodableValue(y_arg),
        });
    channel.Send(encoded_api_arguments,
        [channel_name, on_success = std::move(on_success),
         on_error = std::move(on_error)] (const uint8_t *reply, size_t reply_size)
    {
        std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
        const auto& encodable_return_value = *response;
        const auto *list_return_value = std::get_if<EncodableList>(&encodable_return_value);
        if (list_return_value)
        {
            if (list_return_value->size() > 1)
            {
                on_error(FlutterError(std::get<std::string>(list_return_value->at(0)),
                    std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
            } else
            {
                on_success();
            }
        } else
        {
            on_error(CreateConnectionError(channel_name));
        }
    });
}
} // namespace sparrow
